/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:992000ea-cf3a-45a8-ace7-3c0ca8513d31",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_pyQyPJwKg",
    "aws_user_pools_web_client_id": "4be2bsv1asj0g3lii05le06o5t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://srrrcfaminc55d3omwtvrlunta.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
